version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017

  fashion_service:
    build: ./fashion_service
    ports:
      - "8001:8001"

  home_decor_service:
    build: ./home_decor_service
    ports:
      - "8002:8002"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
