version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  fashion_service:
    build: ./fashion_service
    container_name: fashion_service
    ports:
      - "8001:8000"
    depends_on:
      - mongo

  home_decor_service:
    build: ./home_decor_service
    container_name: home_decor_service
    ports:
      - "8002:8000"
    depends_on:
      - mongo

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8003:8000"
    depends_on:
      - mongo

volumes:
  mongo-data:
